version: '3.1'
services:
  backend:
    image: 'kopsoyleydi/task-manager'
    container_name: 'self-generated-backend-container'
    depends_on:
      - mysqldb
    environment:
      - SERVER_PORT=9999
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_DATASOURCE_URL=jdbc:mysql://mysqldb:3306/mysql
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_SHOW_SQL=true
    ports:
      - 8000:9999

  mysqldb:
    image: mysql
    container_name: 'mysql-container'
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=mysql
    ports:
      - 33060:3306
